services:
  twitch_db:
    image: postgres:18-alpine
    container_name: twitch_db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    volumes:
      - twitch_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - twitch_network
    env_file:
      - ../../.env

networks:
  twitch_network:
    external: true
    name: twitch_network
    driver: bridge

volumes:
  twitch_data:
    driver: local
